---
# tasks file for resolv_conf
- name: Fix DNS
  copy:
    dest: /etc/resolv.conf
    content: |
      search enbridge.com cnpl.enbridge.com egd.enbridge.com gtna.gt.ds uspl.enbridge.com
      nameserver 10.28.43.53
      nameserver 10.33.180.53
      nameserver 10.66.180.53
