---
# tasks file for limits_conf
- name: Limits config
  vars:
    memory: "{{ (ansible_memtotal_mb *1024*1024*0.9/1024)|int }}"
  blockinfile:
    path: /etc/security/limits.conf
    state: present
    block: |
      oracle   soft   nofile    1024
      oracle   hard   nofile    65536
      oracle   soft   nproc    16384
      oracle   hard   nproc    32768
      oracle   soft   stack    10240
      oracle   hard   stack    unlimited
      oracle   soft   memlock  {{ memory }}
      oracle   hard   memlock  {{ memory }}
