---
# tasks file for dis_selinux
- name: Disable selinux
  lineinfile:
      path: /etc/selinux/config
      regexp: '(SELINUX=.*)'
      line: 'SELINUX=disabled'
      backrefs: yes
      state: present
- name: Add SELINUX
  lineinfile:
      path: /etc/selinux/config
      line: "SELINUX=disabled"
      state: present
