---
# tasks file for kernel_conf
- name: Kernel Config
  vars:
    hugepages: "{{ (ansible_memtotal_mb *1024*0.7/2048)|int }}"
  copy:
    dest: /etc/sysctl.conf
    content: |
      kernel.sem = 250 32000 100 128
      kernel.shmall = 18446744073692774399
      kernel.shmmax = 18446744073692774399
      kernel.shmmni = 4096
      kernel.panic_on_oops = 1
      fs.file-max = 6815744
      fs.aio-max-nr = 1048576
      net.ipv4.ip_local_port_range = 9000 65500
      net.core.rmem_default = 262144
      net.core.rmem_max = 4194304
      net.core.wmem_default = 262144
      net.core.wmem_max = 1048576
      vm.nr_hugepages = {{ hugepages }}
      kernel.numa_balancing = 0
#      net.ipv4.ip_forward = 0
      # Do not accept source routing
#      net.ipv4.conf.default.accept_source_route = 0
#      kernel.sysrq = 0
#      kernel.core_uses_pid = 1
#      net.ipv4.tcp_syncookies = 1
#      kernel.msgmnb = 65536
#      kernel.msgmax = 65536
#      fs.file-max = 6815744
#      kernel.sem = 250 32000 100 128
#      kernel.shmmni = 4096
#      kernel.shmall = 18446744073692774399
#      kernel.shmmax = 18446744073692774399
#      kernel.panic_on_oops = 1
#      net.core.rmem_default = 262144
#      net.core.rmem_max = 4194304
#      net.core.wmem_default = 262144
#      net.core.wmem_max = 1048576
#      net.ipv4.conf.all.rp_filter = 2
#      net.ipv4.conf.default.rp_filter = 2
#      fs.aio-max-nr = 1048576
#      net.ipv4.ip_local_port_range = 9000 65500
#      vm.nr_hugepages = 206438
